<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Click;

/**
 * ClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClickRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateClick($link) {
        try {

            $click = new Click();
            $click->setCreatesTs(new \DateTime());
            $click->setLink($link);
            $click->setRequest($_REQUEST);
            $click->setIp($_SERVER['REMOTE_ADDR']);

            $this->getEntityManager()->persist($click);
            $this->getEntityManager()->flush();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
