<?php

namespace AppBundle\Repository;

use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository {

    public function addImpression($linkId) {
        try {

            $query = $this->createQueryBuilder('l')
                    ->select('s.id AS id, s.impressions AS impressions')
                    ->innerJoin('AppBundle:Stats', 's', 'WITH', 's.link = l.id')
                    ->where('l.id = :id')
                    ->setParameter('id', $linkId)
                    ->getQuery();

            return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getAll() {
        try {

            $query = $this->getEntityManager()->createQueryBuilder()
                ->select('l')
                ->from('AppBundle:Link', 'l')
                ->getQuery();

            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function getLinkById($linkId) {
        try {

            $query = $this->getEntityManager()->createQueryBuilder()
                ->select('l')
                ->from('AppBundle:Link', 'l')
                ->andWhere('l.id = :id')
                ->setParameter('id', $linkId)
                ->getQuery();

            return $query->getOneOrNullResult();
   
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function updateLinkData($form) {
        try {
            
            $id = $form->get('id')->getData();

            $em = $this->getEntityManager();
            $linkEdit = $em->getRepository('AppBundle:Link')->find($id);
            
            if (!$linkEdit) {
                throw $this->createNotFoundException(
                        'No product found for id : ' . $linkId
                );
            }
            
            //Get the data from the form
            $name           = $form->get('name')->getData();
            $destination    = $form->get('destination')->getData();
            $serializer     = new Serializer(array(new DateTimeNormalizer()));
            $dateAsObject   = $serializer->denormalize(date("Y-m-d H:i:s"), \DateTimeInterface::class);
       
            $linkEdit->setName($name);
            $linkEdit->setDestination($destination);
            $linkEdit->setCreateTs($dateAsObject);

            $em->flush();
   
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
}
